name: skRayFall
description: An addon for skript that adds Citizens support, EffectLib support and other features.
author: eyesniper2
website: http://sk.rayfall.net/
main: net.rayfall.eyesniper2.skRayFall.skRayFall
version: 1.9.4
depend: [Skript]
softdepend: [Citizens, EffectLib, Votifier, ProtocolLib, Builder, HolographicDisplays, Sentry, CrackShot, CoreProtect]
commands:
  skrayfall:
    description: Base for all skRayFall commands.
    aliases: [rayfall, skrf]
    usage: /skrayfall <reload>