name: skRayFall
description: An addon for skript that adds Citizens support, EffectLib support and other features.
author: eyesniper2
website: http://rayfall.net/
main: net.rayfall.eyesniper2.skRayFall.skRayFall
version: 1.6.2
depend: [Skript]
softdepend: [Citizens, EffectLib, Votifier, ProtocolLib, Builder, HolographicDisplays, Sentry, CrackShot]
commands:
  skrayfall:
    description: Base for all skRayFall commands.
    usage: /skrayfall <reload|createeffect> [effectname] [effectType]